/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vetor.cubo;

import java.awt.Color;

/**
 *
 * @author winky
 */
public class VetorSwing extends javax.swing.JFrame {

    static int vetor1a[] = {1,1,1};
    static int vetor2a[] = {2,2,2};
    static int vetor3a[] = {3,3,3};
    static int vetor4a[] = {4,4,4};
    
     void girocb(){
        for(int c=0;c<3;c++){
            
            int vetorg[] = new int[3];
            vetorg[c] = vetor1a[c];
            vetor1a[c] = vetor2a[c];
            vetor2a[c] = vetor3a[c];
            vetor3a[c] = vetor4a[c];
            vetor4a[c] = vetorg[c];
        }
    }
     void girobc(){
        for(int c=0;c<3;c++){
            
            int vetorg[] = new int[3];
            vetorg[c] = vetor1a[c];
            vetor1a[c] = vetor4a[c];
            vetor4a[c] = vetor3a[c];
            vetor3a[c] = vetor2a[c];
            vetor2a[c] = vetorg[c];
        }
    }
     void cores(){
        lbl2.setOpaque(rootPaneCheckingEnabled);
        lbl2b.setOpaque(rootPaneCheckingEnabled);
        lbl3b.setOpaque(rootPaneCheckingEnabled);
        if(vetor1a[0]==1){
            lbl2.setBackground(Color.red);
        }
        if(vetor1a[1]==1){
            lbl2b.setBackground(Color.red);
        }
        if(vetor1a[2]==1){
            lbl3b.setBackground(Color.red);
        }
        if(vetor1a[0]==2){
            lbl2.setBackground(Color.blue);
        }
        if(vetor1a[1]==2){
            lbl2b.setBackground(Color.blue);
        }
        if(vetor1a[2]==2){
            lbl3b.setBackground(Color.blue);
        }
        if(vetor1a[0]==3){
            lbl2.setBackground(Color.green);
        }
        if(vetor1a[1]==3){
            lbl2b.setBackground(Color.green);
        }
        if(vetor1a[2]==3){
            lbl3b.setBackground(Color.green);
        }
        if(vetor1a[0]==4){
            lbl2.setBackground(Color.yellow);
        }
        if(vetor1a[1]==4){
            lbl2b.setBackground(Color.yellow);
        }
        if(vetor1a[2]==4){
            lbl3b.setBackground(Color.yellow);
        }
    }
    
    public VetorSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl2b = new javax.swing.JLabel();
        lbl3b = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btncb = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl2c = new javax.swing.JLabel();
        lbl3c = new javax.swing.JLabel();
        lbl1a = new javax.swing.JLabel();
        lbl1b = new javax.swing.JLabel();
        lbl1c = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl2b.setBackground(new java.awt.Color(255, 0, 0));
        lbl2b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lbl3b.setBackground(new java.awt.Color(255, 51, 51));
        lbl3b.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lbl2.setBackground(new java.awt.Color(255, 51, 51));
        lbl2.setDisplayedMnemonic('\n');
        lbl2.setLabelFor(this);
        lbl2.setToolTipText("");
        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl2.setEnabled(false);
        lbl2.setFocusable(false);
        lbl2.setInheritsPopupMenu(false);
        lbl2.setRequestFocusEnabled(false);
        lbl2.setVerifyInputWhenFocusTarget(false);

        btncb.setText("Acima");
        btncb.setActionCommand("");
        btncb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbActionPerformed(evt);
            }
        });

        jButton2.setText("Abaixo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl2c.setBackground(new java.awt.Color(255, 51, 51));
        lbl2c.setDisplayedMnemonic('\n');
        lbl2c.setLabelFor(this);
        lbl2c.setToolTipText("");
        lbl2c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl2c.setEnabled(false);
        lbl2c.setFocusable(false);
        lbl2c.setInheritsPopupMenu(false);
        lbl2c.setRequestFocusEnabled(false);
        lbl2c.setVerifyInputWhenFocusTarget(false);

        lbl3c.setBackground(new java.awt.Color(255, 51, 51));
        lbl3c.setDisplayedMnemonic('\n');
        lbl3c.setLabelFor(this);
        lbl3c.setToolTipText("");
        lbl3c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl3c.setEnabled(false);
        lbl3c.setFocusable(false);
        lbl3c.setInheritsPopupMenu(false);
        lbl3c.setRequestFocusEnabled(false);
        lbl3c.setVerifyInputWhenFocusTarget(false);

        lbl1a.setBackground(new java.awt.Color(255, 51, 51));
        lbl1a.setDisplayedMnemonic('\n');
        lbl1a.setLabelFor(this);
        lbl1a.setToolTipText("");
        lbl1a.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl1a.setEnabled(false);
        lbl1a.setFocusable(false);
        lbl1a.setInheritsPopupMenu(false);
        lbl1a.setRequestFocusEnabled(false);
        lbl1a.setVerifyInputWhenFocusTarget(false);

        lbl1b.setBackground(new java.awt.Color(255, 51, 51));
        lbl1b.setDisplayedMnemonic('\n');
        lbl1b.setLabelFor(this);
        lbl1b.setToolTipText("");
        lbl1b.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl1b.setEnabled(false);
        lbl1b.setFocusable(false);
        lbl1b.setInheritsPopupMenu(false);
        lbl1b.setRequestFocusEnabled(false);
        lbl1b.setVerifyInputWhenFocusTarget(false);

        lbl1c.setBackground(new java.awt.Color(255, 51, 51));
        lbl1c.setDisplayedMnemonic('\n');
        lbl1c.setLabelFor(this);
        lbl1c.setToolTipText("");
        lbl1c.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lbl1c.setEnabled(false);
        lbl1c.setFocusable(false);
        lbl1c.setInheritsPopupMenu(false);
        lbl1c.setRequestFocusEnabled(false);
        lbl1c.setVerifyInputWhenFocusTarget(false);

        dd.setBackground(new java.awt.Color(255, 51, 51));
        dd.setDisplayedMnemonic('\n');
        dd.setLabelFor(this);
        dd.setToolTipText("");
        dd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dd.setEnabled(false);
        dd.setFocusable(false);
        dd.setInheritsPopupMenu(false);
        dd.setRequestFocusEnabled(false);
        dd.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncb)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl3b, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2b, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl2c, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3c, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btncb)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1a, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl2b, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2c, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1b, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl3b, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3c, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1c, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbActionPerformed
        cores();
        girobc();
        
        lbl2.setText(Integer.toString(vetor1a[0]));
        lbl2b.setText(Integer.toString(vetor1a[1]));
        lbl3b.setText(Integer.toString(vetor1a[2]));

    }//GEN-LAST:event_btncbActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cores();
        girocb();

        lbl2.setText(Integer.toString(vetor1a[0]));
        lbl2b.setText(Integer.toString(vetor1a[1]));
        lbl3b.setText(Integer.toString(vetor1a[2]));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetorSwing().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncb;
    private javax.swing.JLabel dd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl1a;
    private javax.swing.JLabel lbl1b;
    private javax.swing.JLabel lbl1c;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl2b;
    private javax.swing.JLabel lbl2c;
    private javax.swing.JLabel lbl3b;
    private javax.swing.JLabel lbl3c;
    // End of variables declaration//GEN-END:variables
}
